### ISSUE TITLE
Latest commit broke this sample

### ISSUE THREAD

**Issue by ritazh** [amlsamples/cntk#2]
Hi @hning86 seems the last [commit](https://github.com/amlsamples/cntk/commit/0f41fe969254fabd1118cbb7141a05e4ff04bb3b) broke this sample. 

Error log:
```
...
  File "cntk_mnist.py", line 235, in <module>
    errors.append(float(error))
ValueError: could not convert string to float: 'NA'
```

**Comment by hning86** [comment]
already fixed.
